### PR TITLE
[new] Add comment recognition

### PR DESCRIPTION
**Pull request by marzapower**
The `kCommentBeginChar` will mark the beginning of a single comment line
Given the simple structure of the file, it's probably useless to handle multi-line comments.
The proposed char '#' is inspired by ruby.

### CODE REVIEW

**Comment by NatWeiss** [comment]
Awesome. Thanks for submitting this! I also want to be able to have mid-line comments and for the comment delineator to be multiple characters (as in the C++ style // comment), so will have to play around with this before merging.

**Comment by marzapower** [comment]
Are you looking for something like this?

```
a 1
  b // New dictionary here
    c 1
    d 2
    e 3
    // And so on
    ...
```

**Comment by NatWeiss** [comment]
Right.

**Comment by NatWeiss** [comment]
Merging and trying this out...

**Comment by NatWeiss** [comment]
Nice Marza! Works really well.

I just checked in a [performance improvement](https://github.com/NatWeiss/ValTree/commit/f8f5ab954b30df310bc52e5c7879186b48012393) for queries.

**Comment by marzapower** [comment]
Nice!!!

On Friday, 30 October 2015, Nathanael Weiss notifications@github.com
wrote:

> Nice Marza! Works really well.
> 
> I just checked in a performance improvement
> https://github.com/NatWeiss/ValTree/commit/f8f5ab954b30df310bc52e5c7879186b48012393
> for queries.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NatWeiss/ValTree/pull/2#issuecomment-152376182.

## 

Ing. Daniele Di Bernardo

**Pull request merged**
